version: '3.8'

services:
  backend:
    build:
      context: ./demo-drf
      dockerfile: Dockerfile
    restart: always

  frontend:
    build:
      context: ./demo-next
      dockerfile: Dockerfile
    restart: always

  proxy:
    build:
      context: ./demo-proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - frontend
      - backend
