# Generated by Django 5.0.4 on 2024-04-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitemmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitemmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
